### ISSUE TITLE
Conflict with AdGuard Extension 2.0 beta.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/OmniSidebar#81]
When left clicking on the sidebar title, the context menu is missing the 'Bookmarks' name.  There is just a blank spot. Name appears when I disable AGE and restart Fx.

Here's the page where you will find the AdGuard Extension 2.0 beta:

https://github.com/AdguardTeam/AdguardBrowserExtension/releases

Use either of the XPI files. I had problems installing them by clicking on the XPI file.  I had to save them to my hard drive and then use the option 'Install add-on from file' in 'about:addons' under the Options button, top right.

**Comment by streetwolf** [comment]
Luis...

My problem only happens when you have BOTH AdGuard for Windows installed and the AdGuard Extension.  The two are designed to live together.  When I install just AdGuard Extension on a new profile with OSB I don't get a missing Bookmarks.

Also, the missing Bookmarks also happens on the Menu Bar ... View|Sidebar when using both.

**Comment by Quicksaver** [comment]
That makes sense, the sidebar title menu is directly copied from the View|Sidebar menu. If OSB is disabled (only the AdGuard ext+windows) does the View|Sidebar Bookmarks entry also disappear or is it there as normal?

**Comment by streetwolf** [comment]
With only OSB disabled View|Sidebar Bookmarks does not disappear.

**Comment by streetwolf** [comment]
Screenshot of the problem:

http://i.imgur.com/hUS0qP3.jpg

**Comment by Quicksaver** [comment]
That complicates things. I'll try to take a look soon (I'm on a roll with FindBar Tweak, don't want to stop now). :)

**Comment by streetwolf** [comment]
Here's the post I left on the AdGuard Forum about the conflict.  Maybe you can get an insight as to what the problem might be by asking the developer.

http://forum.adguard.com/showthread.php?4752-Beta-2-0-Conflict-Quicksaver-OmniSidebar

**Comment by streetwolf** [comment]
Just discovered something quirky. If I exit out of Firefox and don't start it again for say 5 minutes,  Bookmarks will be displayed.  Exiting Fx then starting it up again right away usually makes it go missing again.  This leads me to believe that AG for Windows might be the catalyst.  Perhaps it does some sort of processing when I wasn't in Fx.  Just guessing.

**Comment by streetwolf** [comment]
Seems like I might be wrong that both AG for Windows and AG Extension need to be running.  I closed out AG for Windows and Bookmarks always appeared.  So it appears the conflict is between AG Extension and OSB.

Also there are times when I start Fx that Bookmarks appears.  A subsequent restart of Fx usually makes it go AWOL but there were some times it appeared.  I think, but not sure, that if I do nothing on my machine for some time Bookmarks will appear when I fire up Fx.

**Comment by streetwolf** [comment]
I can confirm that if I exit Fx and don't use it for some amount of time (i'd say more than 10 minutes) the Bookmarks name will display as long as I don't exit Fx.  If I do and then start it again in some period of time (short) the Bookmarks name won't appear.  Btw... Even though the name is not there I can still click on it and open up the Bookmarks sidebar so it's a visual anomaly.

Perhaps the longer wait time is allowing AG to do some processing that clears up the problem. Just guessing.

**Comment by streetwolf** [comment]
I was playing around with DOMi and I see that the Bookmarks name disappears because something is deleting the Label parameter.  Maybe this will narrow down the problem for you.

**Comment by Quicksaver** [comment]
I quickly tried AG but I'm not seeing this behavior. Could you please try OSB's latest beta version 1.6b1 (https://addons.mozilla.org/firefox/addon/omnisidebar/versions/) and the latest AG (I tried 2.0.11) and see if this is still happening for you?

**Comment by streetwolf** [comment]
Luis…

 

 

Do you want to use TeamViewer to get on my machine and I can show you what’s happening?  Let me know and I’ll send you the codes.

**Comment by streetwolf** [comment]
Really weird.  Now the problem seems to be a conflict with the add-on called FlashStopper Version e10s-1.2.5b2.  It's an e10s version but it also works on non-e10s.  With FS disabled Bookmarks is displayed.  

You can get this version here:
https://addons.mozilla.org/en-US/firefox/addon/flashstopper/versions/?page=1#version-e10s-1.2.5b2

**Comment by streetwolf** [comment]
Luis...

Just close this.  I've been doing all kinds of testing and I came up with many ways to fix the problem or make the problem.  The thing is I can't narrow it down to one thing.  Really, really weird.  So I give up.

**Comment by streetwolf** [comment]
Luis...

Is there anyway I can remove all the stuff you add to the Sidebar entry both in the sidebar and the menu bar.  It would be interesting if your stuff was gone would I get back the Bookmarks entry?

**Comment by Quicksaver** [comment]
If it happens with more add-ons, the problem is likely with OSB itself. ;)

The thing is I *kinda* know what's happening, I just didn't think it was possible, which is why at the time you first reported this I said "That complicates things". I meant that literally, as the case where this is happened shouldn't really be possible. But I guess it is...

Could you give v1.6b3 a try and see if that helps? https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b3

**Comment by streetwolf** [comment]
Luis…

 

Yep, that fixed it.   Leave it to me to find the impossible or now improbable.  Like the in content options .  

 

There is one problem I see so far.  The sidebar always opens with History even though Fx was closed with something else like Bookmarks.

**Comment by Quicksaver** [comment]
That's weird, it's remembering the correct sidebar for me. Can you tell if anything appear in the error console (Ctrl+Shift+J) about the add-on during startup or when you open any sidebar?

By the way, could you also try restarting the browser again? I have a feeling...

**Comment by streetwolf** [comment]
OK.  I had to use the sidebar menu to check Bookmarks to get it to be the default.  Probably due to the fact that I place the bookmarks and History icons on the OSB toolbar.  I also don’t display the sidebar title. OSB doesn’t seem to remember the sidebar I last used it I use my icons.  I think some more work is needed in this area.

**Comment by streetwolf** [comment]
It seems that it’s just Bookmarks that I am having problems with using my Bookmarks icon.  I see that Bookmarks never gets checked in the sidebar menu.  My History icon does produce a check mark on the History menu option.  So it’s a Bookmarks issue again but in a different form.

**Comment by Quicksaver** [comment]
Yep, you're right on the money, I screwed up that fix. Have to try again...

**Comment by streetwolf** [comment]
Send me the update when you finish it.

**Comment by Quicksaver** [comment]
Try v1.6b5 https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b5

The bookmarks button should now work correctly. Could you check if the bookmarks menu entry keeps its value this way?

**Comment by streetwolf** [comment]
Bad news..  Things are back to the way they were, ie the Bookmarks entry is missing again.  Behaves like before these betas.

**Comment by Quicksaver** [comment]
Ok enough playing nice, time for a precision strike. Tell me about v1.6b6 https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b6

**Comment by streetwolf** [comment]
After I installed it I restarted Fx and saw that Bookmarks was still missing.  However, after another Fx restart it appeared and all seems OK for now.

----- Original Message -----

**Comment by Quicksaver** [comment]
Let me know if it disappears again, I might need to go with a more aggressive approach if it does.
